snakemake_rules:
  tier_raw_mgdo:
    inputs: {}
    options:
      logging: $_/log/basic_logging.yaml
      logger: prod

  tier_tcm:
    inputs:
      config: $_/tier/tcm/sp01-p%-r%-T%-all-config.yaml
    options:
      logging: $_/log/basic_logging.yaml
      logger: prod
