- valid_from: 20231012T163000Z
  mode: reset
  apply:
    - sp01-p01-r%-T%-all-config.yaml

- valid_from: 20240805T173003Z
  mode: reset
  apply:
    - sp02-p01-r%-T%-all-config.yaml

- valid_from: 20241218T104123Z
  mode: reset
  apply:
    - sp03-p01-r%-T%-all-config.yaml

- valid_from: 20250214T173002Z
  mode: reset
  apply:
    - sp04-p01-r%-T%-all-config.yaml
